version: '3.9'

services:
  mongo:
    container_name: mydatabase
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/app/dbdata
  server:
    build: .
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "4000:4000"
    links:
      - mongo